/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:    
 * Created:   
 * Copyright: 
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation 
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	SetTopWindow( new MainFrame( NULL ) );
	GetTopWindow()->Show();
	
	// true = enter the main loop
	return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation 
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow *parent) 
: MainFrameBase( parent )
, m_pLogEntry(NULL)
{
	m_pLogEntry = new LogEntry(true, "", m_stcLog);
	wxLog::SetActiveTarget(m_pLogEntry);
	wxLogMessage("Log Inited.");
}

MainFrame::~MainFrame()
{
 	wxLog::SetActiveTarget(NULL);
 	delete m_pLogEntry;
}

void MainFrame::OnCloseFrame(wxCloseEvent& event)
{
	Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent& event)
{
	Destroy();
}


#include "C21.h"
void MainFrame::m_toolTestOnToolClicked(wxCommandEvent& event)
{
	SqListTest();
	LkListTest();
}
