/*********************************************************************
 * Name:      	main.h
 * Purpose:   	Declares simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:    
 * Created:   
 * Copyright: 
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is declared in
 * 				gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"

#include "..\tinyxml2\tinyxml2.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration 
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
	public:
		virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration 
////////////////////////////////////////////////////////////////////////////////

class MainFrame : public MainFrameBase
{
	public:
		MainFrame( wxWindow *parent );
		virtual ~MainFrame();
		
	protected:
		// protected event handlers
		virtual void OnCloseFrame( wxCloseEvent& event );
		virtual void OnMenuFileOpen( wxCommandEvent& event );


		virtual void OnMenuFileExpand( wxCommandEvent& event );
		virtual void OnExitClick( wxCommandEvent& event );

		// control event handlers
		virtual void dirExplorerOnTreeItemActivated( wxTreeEvent& event );
		virtual void buttonDefaultOnButtonClick( wxCommandEvent& event );
		virtual void buttonSaveOnButtonClick( wxCommandEvent& event );
		virtual void dvlistConfigOnDataViewListCtrlItemActivated( wxDataViewEvent& event );
		virtual void dvlistConfigOnDataViewListCtrlItemEditingDone( wxDataViewEvent& event ) ;

		// members
		wxString m_strXmlFileName;
		tinyxml2::TiDocument m_xmlDoc;

		// user functions
		void LoadFile();

		void LoadConfig();
};

#endif //__main__
