/* soapH.h
   Generated by gSOAP 2.8.22 from wth.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult
#define SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char*, int, const _ns1__getSupportDataSetResponse_getSupportDataSetResult *, const char*);
SOAP_FMAC3 _ns1__getSupportDataSetResponse_getSupportDataSetResult * SOAP_FMAC4 soap_in__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char*, _ns1__getSupportDataSetResponse_getSupportDataSetResult *, const char*);

#ifndef soap_write__ns1__getSupportDataSetResponse_getSupportDataSetResult
#define soap_write__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getSupportDataSetResponse-getSupportDataSetResult", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportDataSetResponse_getSupportDataSetResult * SOAP_FMAC4 soap_get__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, _ns1__getSupportDataSetResponse_getSupportDataSetResult *, const char*, const char*);

#ifndef soap_read__ns1__getSupportDataSetResponse_getSupportDataSetResult
#define soap_read__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getSupportDataSetResponse_getSupportDataSetResult * SOAP_FMAC2 soap_instantiate__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getSupportDataSetResponse_getSupportDataSetResult * soap_new__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, n, NULL, NULL, NULL); }

inline _ns1__getSupportDataSetResponse_getSupportDataSetResult * soap_new_req__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap *soap, char *xsd__schema) { _ns1__getSupportDataSetResponse_getSupportDataSetResult *_p = soap_instantiate__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getSupportDataSetResponse_getSupportDataSetResult::xsd__schema = xsd__schema; } return _p; }

inline _ns1__getSupportDataSetResponse_getSupportDataSetResult * soap_new_set__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap *soap, char *xsd__schema, char *__any) { _ns1__getSupportDataSetResponse_getSupportDataSetResult *_p = soap_instantiate__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getSupportDataSetResponse_getSupportDataSetResult::xsd__schema = xsd__schema; _p->_ns1__getSupportDataSetResponse_getSupportDataSetResult::__any = __any; } return _p; }

inline void soap_delete__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap *soap, _ns1__getSupportDataSetResponse_getSupportDataSetResult *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__DataSet
#define SOAP_TYPE__ns1__DataSet (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__DataSet(struct soap*, const char*, int, const _ns1__DataSet *, const char*);
SOAP_FMAC3 _ns1__DataSet * SOAP_FMAC4 soap_in__ns1__DataSet(struct soap*, const char*, _ns1__DataSet *, const char*);

#ifndef soap_write__ns1__DataSet
#define soap_write__ns1__DataSet(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:DataSet", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__DataSet * SOAP_FMAC4 soap_get__ns1__DataSet(struct soap*, _ns1__DataSet *, const char*, const char*);

#ifndef soap_read__ns1__DataSet
#define soap_read__ns1__DataSet(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__DataSet(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__DataSet * SOAP_FMAC2 soap_instantiate__ns1__DataSet(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__DataSet * soap_new__ns1__DataSet(struct soap *soap, int n = -1) { return soap_instantiate__ns1__DataSet(soap, n, NULL, NULL, NULL); }

inline _ns1__DataSet * soap_new_req__ns1__DataSet(struct soap *soap, char *xsd__schema) { _ns1__DataSet *_p = soap_instantiate__ns1__DataSet(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__DataSet::xsd__schema = xsd__schema; } return _p; }

inline _ns1__DataSet * soap_new_set__ns1__DataSet(struct soap *soap, char *xsd__schema, char *__any) { _ns1__DataSet *_p = soap_instantiate__ns1__DataSet(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__DataSet::xsd__schema = xsd__schema; _p->_ns1__DataSet::__any = __any; } return _p; }

inline void soap_delete__ns1__DataSet(struct soap *soap, _ns1__DataSet *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__DataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNameProResponse
#define SOAP_TYPE__ns1__getWeatherbyCityNameProResponse (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityNameProResponse(struct soap*, const char*, int, const _ns1__getWeatherbyCityNameProResponse *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameProResponse * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityNameProResponse(struct soap*, const char*, _ns1__getWeatherbyCityNameProResponse *, const char*);

#ifndef soap_write__ns1__getWeatherbyCityNameProResponse
#define soap_write__ns1__getWeatherbyCityNameProResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getWeatherbyCityNameProResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getWeatherbyCityNameProResponse * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse *, const char*, const char*);

#ifndef soap_read__ns1__getWeatherbyCityNameProResponse
#define soap_read__ns1__getWeatherbyCityNameProResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getWeatherbyCityNameProResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getWeatherbyCityNameProResponse * SOAP_FMAC2 soap_instantiate__ns1__getWeatherbyCityNameProResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getWeatherbyCityNameProResponse * soap_new__ns1__getWeatherbyCityNameProResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getWeatherbyCityNameProResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__getWeatherbyCityNameProResponse * soap_new_req__ns1__getWeatherbyCityNameProResponse(struct soap *soap) { _ns1__getWeatherbyCityNameProResponse *_p = soap_instantiate__ns1__getWeatherbyCityNameProResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getWeatherbyCityNameProResponse * soap_new_set__ns1__getWeatherbyCityNameProResponse(struct soap *soap, ns1__ArrayOfString *getWeatherbyCityNameProResult) { _ns1__getWeatherbyCityNameProResponse *_p = soap_instantiate__ns1__getWeatherbyCityNameProResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getWeatherbyCityNameProResponse::getWeatherbyCityNameProResult = getWeatherbyCityNameProResult; } return _p; }

inline void soap_delete__ns1__getWeatherbyCityNameProResponse(struct soap *soap, _ns1__getWeatherbyCityNameProResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityNameProResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNamePro
#define SOAP_TYPE__ns1__getWeatherbyCityNamePro (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityNamePro(struct soap*, const char*, int, const _ns1__getWeatherbyCityNamePro *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityNamePro(struct soap*, const char*, _ns1__getWeatherbyCityNamePro *, const char*);

#ifndef soap_write__ns1__getWeatherbyCityNamePro
#define soap_write__ns1__getWeatherbyCityNamePro(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getWeatherbyCityNamePro", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro *, const char*, const char*);

#ifndef soap_read__ns1__getWeatherbyCityNamePro
#define soap_read__ns1__getWeatherbyCityNamePro(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getWeatherbyCityNamePro(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getWeatherbyCityNamePro * SOAP_FMAC2 soap_instantiate__ns1__getWeatherbyCityNamePro(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getWeatherbyCityNamePro * soap_new__ns1__getWeatherbyCityNamePro(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getWeatherbyCityNamePro(soap, n, NULL, NULL, NULL); }

inline _ns1__getWeatherbyCityNamePro * soap_new_req__ns1__getWeatherbyCityNamePro(struct soap *soap) { _ns1__getWeatherbyCityNamePro *_p = soap_instantiate__ns1__getWeatherbyCityNamePro(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getWeatherbyCityNamePro * soap_new_set__ns1__getWeatherbyCityNamePro(struct soap *soap, char *theCityName, char *theUserID) { _ns1__getWeatherbyCityNamePro *_p = soap_instantiate__ns1__getWeatherbyCityNamePro(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getWeatherbyCityNamePro::theCityName = theCityName; _p->_ns1__getWeatherbyCityNamePro::theUserID = theUserID; } return _p; }

inline void soap_delete__ns1__getWeatherbyCityNamePro(struct soap *soap, _ns1__getWeatherbyCityNamePro *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityNamePro(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNameResponse
#define SOAP_TYPE__ns1__getWeatherbyCityNameResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityNameResponse(struct soap*, const char*, int, const _ns1__getWeatherbyCityNameResponse *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameResponse * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityNameResponse(struct soap*, const char*, _ns1__getWeatherbyCityNameResponse *, const char*);

#ifndef soap_write__ns1__getWeatherbyCityNameResponse
#define soap_write__ns1__getWeatherbyCityNameResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getWeatherbyCityNameResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getWeatherbyCityNameResponse * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse *, const char*, const char*);

#ifndef soap_read__ns1__getWeatherbyCityNameResponse
#define soap_read__ns1__getWeatherbyCityNameResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getWeatherbyCityNameResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getWeatherbyCityNameResponse * SOAP_FMAC2 soap_instantiate__ns1__getWeatherbyCityNameResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getWeatherbyCityNameResponse * soap_new__ns1__getWeatherbyCityNameResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getWeatherbyCityNameResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__getWeatherbyCityNameResponse * soap_new_req__ns1__getWeatherbyCityNameResponse(struct soap *soap) { _ns1__getWeatherbyCityNameResponse *_p = soap_instantiate__ns1__getWeatherbyCityNameResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getWeatherbyCityNameResponse * soap_new_set__ns1__getWeatherbyCityNameResponse(struct soap *soap, ns1__ArrayOfString *getWeatherbyCityNameResult) { _ns1__getWeatherbyCityNameResponse *_p = soap_instantiate__ns1__getWeatherbyCityNameResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getWeatherbyCityNameResponse::getWeatherbyCityNameResult = getWeatherbyCityNameResult; } return _p; }

inline void soap_delete__ns1__getWeatherbyCityNameResponse(struct soap *soap, _ns1__getWeatherbyCityNameResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityNameResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getWeatherbyCityName
#define SOAP_TYPE__ns1__getWeatherbyCityName (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityName(struct soap*, const char*, int, const _ns1__getWeatherbyCityName *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityName * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityName(struct soap*, const char*, _ns1__getWeatherbyCityName *, const char*);

#ifndef soap_write__ns1__getWeatherbyCityName
#define soap_write__ns1__getWeatherbyCityName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getWeatherbyCityName", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getWeatherbyCityName * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName *, const char*, const char*);

#ifndef soap_read__ns1__getWeatherbyCityName
#define soap_read__ns1__getWeatherbyCityName(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getWeatherbyCityName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getWeatherbyCityName * SOAP_FMAC2 soap_instantiate__ns1__getWeatherbyCityName(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getWeatherbyCityName * soap_new__ns1__getWeatherbyCityName(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getWeatherbyCityName(soap, n, NULL, NULL, NULL); }

inline _ns1__getWeatherbyCityName * soap_new_req__ns1__getWeatherbyCityName(struct soap *soap) { _ns1__getWeatherbyCityName *_p = soap_instantiate__ns1__getWeatherbyCityName(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getWeatherbyCityName * soap_new_set__ns1__getWeatherbyCityName(struct soap *soap, char *theCityName) { _ns1__getWeatherbyCityName *_p = soap_instantiate__ns1__getWeatherbyCityName(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getWeatherbyCityName::theCityName = theCityName; } return _p; }

inline void soap_delete__ns1__getWeatherbyCityName(struct soap *soap, _ns1__getWeatherbyCityName *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getSupportDataSetResponse
#define SOAP_TYPE__ns1__getSupportDataSetResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportDataSetResponse(struct soap*, const char*, int, const _ns1__getSupportDataSetResponse *, const char*);
SOAP_FMAC3 _ns1__getSupportDataSetResponse * SOAP_FMAC4 soap_in__ns1__getSupportDataSetResponse(struct soap*, const char*, _ns1__getSupportDataSetResponse *, const char*);

#ifndef soap_write__ns1__getSupportDataSetResponse
#define soap_write__ns1__getSupportDataSetResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getSupportDataSetResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportDataSetResponse * SOAP_FMAC4 soap_get__ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse *, const char*, const char*);

#ifndef soap_read__ns1__getSupportDataSetResponse
#define soap_read__ns1__getSupportDataSetResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getSupportDataSetResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getSupportDataSetResponse * SOAP_FMAC2 soap_instantiate__ns1__getSupportDataSetResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getSupportDataSetResponse * soap_new__ns1__getSupportDataSetResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getSupportDataSetResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__getSupportDataSetResponse * soap_new_req__ns1__getSupportDataSetResponse(struct soap *soap) { _ns1__getSupportDataSetResponse *_p = soap_instantiate__ns1__getSupportDataSetResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getSupportDataSetResponse * soap_new_set__ns1__getSupportDataSetResponse(struct soap *soap, _ns1__getSupportDataSetResponse_getSupportDataSetResult *getSupportDataSetResult) { _ns1__getSupportDataSetResponse *_p = soap_instantiate__ns1__getSupportDataSetResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getSupportDataSetResponse::getSupportDataSetResult = getSupportDataSetResult; } return _p; }

inline void soap_delete__ns1__getSupportDataSetResponse(struct soap *soap, _ns1__getSupportDataSetResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportDataSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getSupportDataSet
#define SOAP_TYPE__ns1__getSupportDataSet (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportDataSet(struct soap*, const char*, int, const _ns1__getSupportDataSet *, const char*);
SOAP_FMAC3 _ns1__getSupportDataSet * SOAP_FMAC4 soap_in__ns1__getSupportDataSet(struct soap*, const char*, _ns1__getSupportDataSet *, const char*);

#ifndef soap_write__ns1__getSupportDataSet
#define soap_write__ns1__getSupportDataSet(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getSupportDataSet", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportDataSet * SOAP_FMAC4 soap_get__ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet *, const char*, const char*);

#ifndef soap_read__ns1__getSupportDataSet
#define soap_read__ns1__getSupportDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getSupportDataSet(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getSupportDataSet * SOAP_FMAC2 soap_instantiate__ns1__getSupportDataSet(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getSupportDataSet * soap_new__ns1__getSupportDataSet(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getSupportDataSet(soap, n, NULL, NULL, NULL); }

inline _ns1__getSupportDataSet * soap_new_req__ns1__getSupportDataSet(struct soap *soap) { _ns1__getSupportDataSet *_p = soap_instantiate__ns1__getSupportDataSet(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getSupportDataSet * soap_new_set__ns1__getSupportDataSet(struct soap *soap) { _ns1__getSupportDataSet *_p = soap_instantiate__ns1__getSupportDataSet(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete__ns1__getSupportDataSet(struct soap *soap, _ns1__getSupportDataSet *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getSupportProvinceResponse
#define SOAP_TYPE__ns1__getSupportProvinceResponse (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportProvinceResponse(struct soap*, const char*, int, const _ns1__getSupportProvinceResponse *, const char*);
SOAP_FMAC3 _ns1__getSupportProvinceResponse * SOAP_FMAC4 soap_in__ns1__getSupportProvinceResponse(struct soap*, const char*, _ns1__getSupportProvinceResponse *, const char*);

#ifndef soap_write__ns1__getSupportProvinceResponse
#define soap_write__ns1__getSupportProvinceResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getSupportProvinceResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportProvinceResponse * SOAP_FMAC4 soap_get__ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse *, const char*, const char*);

#ifndef soap_read__ns1__getSupportProvinceResponse
#define soap_read__ns1__getSupportProvinceResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getSupportProvinceResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getSupportProvinceResponse * SOAP_FMAC2 soap_instantiate__ns1__getSupportProvinceResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getSupportProvinceResponse * soap_new__ns1__getSupportProvinceResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getSupportProvinceResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__getSupportProvinceResponse * soap_new_req__ns1__getSupportProvinceResponse(struct soap *soap) { _ns1__getSupportProvinceResponse *_p = soap_instantiate__ns1__getSupportProvinceResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getSupportProvinceResponse * soap_new_set__ns1__getSupportProvinceResponse(struct soap *soap, ns1__ArrayOfString *getSupportProvinceResult) { _ns1__getSupportProvinceResponse *_p = soap_instantiate__ns1__getSupportProvinceResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getSupportProvinceResponse::getSupportProvinceResult = getSupportProvinceResult; } return _p; }

inline void soap_delete__ns1__getSupportProvinceResponse(struct soap *soap, _ns1__getSupportProvinceResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportProvinceResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getSupportProvince
#define SOAP_TYPE__ns1__getSupportProvince (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportProvince(struct soap*, const char*, int, const _ns1__getSupportProvince *, const char*);
SOAP_FMAC3 _ns1__getSupportProvince * SOAP_FMAC4 soap_in__ns1__getSupportProvince(struct soap*, const char*, _ns1__getSupportProvince *, const char*);

#ifndef soap_write__ns1__getSupportProvince
#define soap_write__ns1__getSupportProvince(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getSupportProvince", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportProvince * SOAP_FMAC4 soap_get__ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince *, const char*, const char*);

#ifndef soap_read__ns1__getSupportProvince
#define soap_read__ns1__getSupportProvince(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getSupportProvince(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getSupportProvince * SOAP_FMAC2 soap_instantiate__ns1__getSupportProvince(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getSupportProvince * soap_new__ns1__getSupportProvince(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getSupportProvince(soap, n, NULL, NULL, NULL); }

inline _ns1__getSupportProvince * soap_new_req__ns1__getSupportProvince(struct soap *soap) { _ns1__getSupportProvince *_p = soap_instantiate__ns1__getSupportProvince(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getSupportProvince * soap_new_set__ns1__getSupportProvince(struct soap *soap) { _ns1__getSupportProvince *_p = soap_instantiate__ns1__getSupportProvince(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete__ns1__getSupportProvince(struct soap *soap, _ns1__getSupportProvince *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportProvince(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getSupportCityResponse
#define SOAP_TYPE__ns1__getSupportCityResponse (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportCityResponse(struct soap*, const char*, int, const _ns1__getSupportCityResponse *, const char*);
SOAP_FMAC3 _ns1__getSupportCityResponse * SOAP_FMAC4 soap_in__ns1__getSupportCityResponse(struct soap*, const char*, _ns1__getSupportCityResponse *, const char*);

#ifndef soap_write__ns1__getSupportCityResponse
#define soap_write__ns1__getSupportCityResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getSupportCityResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportCityResponse * SOAP_FMAC4 soap_get__ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse *, const char*, const char*);

#ifndef soap_read__ns1__getSupportCityResponse
#define soap_read__ns1__getSupportCityResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getSupportCityResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getSupportCityResponse * SOAP_FMAC2 soap_instantiate__ns1__getSupportCityResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getSupportCityResponse * soap_new__ns1__getSupportCityResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getSupportCityResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__getSupportCityResponse * soap_new_req__ns1__getSupportCityResponse(struct soap *soap) { _ns1__getSupportCityResponse *_p = soap_instantiate__ns1__getSupportCityResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getSupportCityResponse * soap_new_set__ns1__getSupportCityResponse(struct soap *soap, ns1__ArrayOfString *getSupportCityResult) { _ns1__getSupportCityResponse *_p = soap_instantiate__ns1__getSupportCityResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getSupportCityResponse::getSupportCityResult = getSupportCityResult; } return _p; }

inline void soap_delete__ns1__getSupportCityResponse(struct soap *soap, _ns1__getSupportCityResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportCityResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getSupportCity
#define SOAP_TYPE__ns1__getSupportCity (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportCity(struct soap*, const char*, int, const _ns1__getSupportCity *, const char*);
SOAP_FMAC3 _ns1__getSupportCity * SOAP_FMAC4 soap_in__ns1__getSupportCity(struct soap*, const char*, _ns1__getSupportCity *, const char*);

#ifndef soap_write__ns1__getSupportCity
#define soap_write__ns1__getSupportCity(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:getSupportCity", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportCity * SOAP_FMAC4 soap_get__ns1__getSupportCity(struct soap*, _ns1__getSupportCity *, const char*, const char*);

#ifndef soap_read__ns1__getSupportCity
#define soap_read__ns1__getSupportCity(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__getSupportCity(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__getSupportCity * SOAP_FMAC2 soap_instantiate__ns1__getSupportCity(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__getSupportCity * soap_new__ns1__getSupportCity(struct soap *soap, int n = -1) { return soap_instantiate__ns1__getSupportCity(soap, n, NULL, NULL, NULL); }

inline _ns1__getSupportCity * soap_new_req__ns1__getSupportCity(struct soap *soap) { _ns1__getSupportCity *_p = soap_instantiate__ns1__getSupportCity(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__getSupportCity * soap_new_set__ns1__getSupportCity(struct soap *soap, char *byProvinceName) { _ns1__getSupportCity *_p = soap_instantiate__ns1__getSupportCity(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__getSupportCity::byProvinceName = byProvinceName; } return _p; }

inline void soap_delete__ns1__getSupportCity(struct soap *soap, _ns1__getSupportCity *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportCity(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfString(struct soap*, const char*, int, const ns1__ArrayOfString *, const char*);
SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_in_ns1__ArrayOfString(struct soap*, const char*, ns1__ArrayOfString *, const char*);

#ifndef soap_write_ns1__ArrayOfString
#define soap_write_ns1__ArrayOfString(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ArrayOfString", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_get_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString *, const char*, const char*);

#ifndef soap_read_ns1__ArrayOfString
#define soap_read_ns1__ArrayOfString(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ArrayOfString(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__ArrayOfString * SOAP_FMAC2 soap_instantiate_ns1__ArrayOfString(struct soap*, int, const char*, const char*, size_t*);

inline ns1__ArrayOfString * soap_new_ns1__ArrayOfString(struct soap *soap, int n = -1) { return soap_instantiate_ns1__ArrayOfString(soap, n, NULL, NULL, NULL); }

inline ns1__ArrayOfString * soap_new_req_ns1__ArrayOfString(struct soap *soap, int __sizestring, char **string) { ns1__ArrayOfString *_p = soap_instantiate_ns1__ArrayOfString(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ArrayOfString::__sizestring = __sizestring; _p->ns1__ArrayOfString::string = string; } return _p; }

inline ns1__ArrayOfString * soap_new_set_ns1__ArrayOfString(struct soap *soap, int __sizestring, char **string) { ns1__ArrayOfString *_p = soap_instantiate_ns1__ArrayOfString(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ArrayOfString::__sizestring = __sizestring; _p->ns1__ArrayOfString::string = string; } return _p; }

inline void soap_delete_ns1__ArrayOfString(struct soap *soap, ns1__ArrayOfString *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfString(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityNamePro_
#define SOAP_TYPE___ns1__getWeatherbyCityNamePro_ (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityNamePro_(struct soap*, struct __ns1__getWeatherbyCityNamePro_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityNamePro_(struct soap*, const struct __ns1__getWeatherbyCityNamePro_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityNamePro_(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityNamePro_ *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro_ * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityNamePro_(struct soap*, const char*, struct __ns1__getWeatherbyCityNamePro_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityNamePro_(struct soap*, const struct __ns1__getWeatherbyCityNamePro_ *, const char*, const char*);

#ifndef soap_write___ns1__getWeatherbyCityNamePro_
#define soap_write___ns1__getWeatherbyCityNamePro_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getWeatherbyCityNamePro_(soap, data), 0) || soap_put___ns1__getWeatherbyCityNamePro_(soap, data, "-ns1:getWeatherbyCityNamePro", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro_ * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityNamePro_(struct soap*, struct __ns1__getWeatherbyCityNamePro_ *, const char*, const char*);

#ifndef soap_read___ns1__getWeatherbyCityNamePro_
#define soap_read___ns1__getWeatherbyCityNamePro_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getWeatherbyCityNamePro_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getWeatherbyCityNamePro_ * SOAP_FMAC2 soap_instantiate___ns1__getWeatherbyCityNamePro_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getWeatherbyCityNamePro_ * soap_new___ns1__getWeatherbyCityNamePro_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getWeatherbyCityNamePro_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getWeatherbyCityNamePro_ * soap_new_req___ns1__getWeatherbyCityNamePro_(struct soap *soap) { struct __ns1__getWeatherbyCityNamePro_ *_p = soap_instantiate___ns1__getWeatherbyCityNamePro_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityNamePro_(soap, _p); } return _p; }

inline struct __ns1__getWeatherbyCityNamePro_ * soap_new_set___ns1__getWeatherbyCityNamePro_(struct soap *soap, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro) { struct __ns1__getWeatherbyCityNamePro_ *_p = soap_instantiate___ns1__getWeatherbyCityNamePro_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityNamePro_(soap, _p); _p->ns1__getWeatherbyCityNamePro = ns1__getWeatherbyCityNamePro; } return _p; }

inline void soap_delete___ns1__getWeatherbyCityNamePro_(struct soap *soap, struct __ns1__getWeatherbyCityNamePro_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityNamePro_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getWeatherbyCityName_
#define SOAP_TYPE___ns1__getWeatherbyCityName_ (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityName_(struct soap*, struct __ns1__getWeatherbyCityName_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityName_(struct soap*, const struct __ns1__getWeatherbyCityName_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityName_(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityName_ *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName_ * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityName_(struct soap*, const char*, struct __ns1__getWeatherbyCityName_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityName_(struct soap*, const struct __ns1__getWeatherbyCityName_ *, const char*, const char*);

#ifndef soap_write___ns1__getWeatherbyCityName_
#define soap_write___ns1__getWeatherbyCityName_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getWeatherbyCityName_(soap, data), 0) || soap_put___ns1__getWeatherbyCityName_(soap, data, "-ns1:getWeatherbyCityName", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getWeatherbyCityName_ * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityName_(struct soap*, struct __ns1__getWeatherbyCityName_ *, const char*, const char*);

#ifndef soap_read___ns1__getWeatherbyCityName_
#define soap_read___ns1__getWeatherbyCityName_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getWeatherbyCityName_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getWeatherbyCityName_ * SOAP_FMAC2 soap_instantiate___ns1__getWeatherbyCityName_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getWeatherbyCityName_ * soap_new___ns1__getWeatherbyCityName_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getWeatherbyCityName_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getWeatherbyCityName_ * soap_new_req___ns1__getWeatherbyCityName_(struct soap *soap) { struct __ns1__getWeatherbyCityName_ *_p = soap_instantiate___ns1__getWeatherbyCityName_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityName_(soap, _p); } return _p; }

inline struct __ns1__getWeatherbyCityName_ * soap_new_set___ns1__getWeatherbyCityName_(struct soap *soap, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName) { struct __ns1__getWeatherbyCityName_ *_p = soap_instantiate___ns1__getWeatherbyCityName_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityName_(soap, _p); _p->ns1__getWeatherbyCityName = ns1__getWeatherbyCityName; } return _p; }

inline void soap_delete___ns1__getWeatherbyCityName_(struct soap *soap, struct __ns1__getWeatherbyCityName_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityName_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getSupportDataSet_
#define SOAP_TYPE___ns1__getSupportDataSet_ (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportDataSet_(struct soap*, struct __ns1__getSupportDataSet_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportDataSet_(struct soap*, const struct __ns1__getSupportDataSet_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportDataSet_(struct soap*, const char*, int, const struct __ns1__getSupportDataSet_ *, const char*);
SOAP_FMAC3 struct __ns1__getSupportDataSet_ * SOAP_FMAC4 soap_in___ns1__getSupportDataSet_(struct soap*, const char*, struct __ns1__getSupportDataSet_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportDataSet_(struct soap*, const struct __ns1__getSupportDataSet_ *, const char*, const char*);

#ifndef soap_write___ns1__getSupportDataSet_
#define soap_write___ns1__getSupportDataSet_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getSupportDataSet_(soap, data), 0) || soap_put___ns1__getSupportDataSet_(soap, data, "-ns1:getSupportDataSet", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getSupportDataSet_ * SOAP_FMAC4 soap_get___ns1__getSupportDataSet_(struct soap*, struct __ns1__getSupportDataSet_ *, const char*, const char*);

#ifndef soap_read___ns1__getSupportDataSet_
#define soap_read___ns1__getSupportDataSet_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSupportDataSet_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getSupportDataSet_ * SOAP_FMAC2 soap_instantiate___ns1__getSupportDataSet_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getSupportDataSet_ * soap_new___ns1__getSupportDataSet_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getSupportDataSet_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getSupportDataSet_ * soap_new_req___ns1__getSupportDataSet_(struct soap *soap) { struct __ns1__getSupportDataSet_ *_p = soap_instantiate___ns1__getSupportDataSet_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportDataSet_(soap, _p); } return _p; }

inline struct __ns1__getSupportDataSet_ * soap_new_set___ns1__getSupportDataSet_(struct soap *soap, _ns1__getSupportDataSet *ns1__getSupportDataSet) { struct __ns1__getSupportDataSet_ *_p = soap_instantiate___ns1__getSupportDataSet_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportDataSet_(soap, _p); _p->ns1__getSupportDataSet = ns1__getSupportDataSet; } return _p; }

inline void soap_delete___ns1__getSupportDataSet_(struct soap *soap, struct __ns1__getSupportDataSet_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportDataSet_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getSupportProvince_
#define SOAP_TYPE___ns1__getSupportProvince_ (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportProvince_(struct soap*, struct __ns1__getSupportProvince_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportProvince_(struct soap*, const struct __ns1__getSupportProvince_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportProvince_(struct soap*, const char*, int, const struct __ns1__getSupportProvince_ *, const char*);
SOAP_FMAC3 struct __ns1__getSupportProvince_ * SOAP_FMAC4 soap_in___ns1__getSupportProvince_(struct soap*, const char*, struct __ns1__getSupportProvince_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportProvince_(struct soap*, const struct __ns1__getSupportProvince_ *, const char*, const char*);

#ifndef soap_write___ns1__getSupportProvince_
#define soap_write___ns1__getSupportProvince_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getSupportProvince_(soap, data), 0) || soap_put___ns1__getSupportProvince_(soap, data, "-ns1:getSupportProvince", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getSupportProvince_ * SOAP_FMAC4 soap_get___ns1__getSupportProvince_(struct soap*, struct __ns1__getSupportProvince_ *, const char*, const char*);

#ifndef soap_read___ns1__getSupportProvince_
#define soap_read___ns1__getSupportProvince_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSupportProvince_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getSupportProvince_ * SOAP_FMAC2 soap_instantiate___ns1__getSupportProvince_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getSupportProvince_ * soap_new___ns1__getSupportProvince_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getSupportProvince_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getSupportProvince_ * soap_new_req___ns1__getSupportProvince_(struct soap *soap) { struct __ns1__getSupportProvince_ *_p = soap_instantiate___ns1__getSupportProvince_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportProvince_(soap, _p); } return _p; }

inline struct __ns1__getSupportProvince_ * soap_new_set___ns1__getSupportProvince_(struct soap *soap, _ns1__getSupportProvince *ns1__getSupportProvince) { struct __ns1__getSupportProvince_ *_p = soap_instantiate___ns1__getSupportProvince_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportProvince_(soap, _p); _p->ns1__getSupportProvince = ns1__getSupportProvince; } return _p; }

inline void soap_delete___ns1__getSupportProvince_(struct soap *soap, struct __ns1__getSupportProvince_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportProvince_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getSupportCity_
#define SOAP_TYPE___ns1__getSupportCity_ (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportCity_(struct soap*, struct __ns1__getSupportCity_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportCity_(struct soap*, const struct __ns1__getSupportCity_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportCity_(struct soap*, const char*, int, const struct __ns1__getSupportCity_ *, const char*);
SOAP_FMAC3 struct __ns1__getSupportCity_ * SOAP_FMAC4 soap_in___ns1__getSupportCity_(struct soap*, const char*, struct __ns1__getSupportCity_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportCity_(struct soap*, const struct __ns1__getSupportCity_ *, const char*, const char*);

#ifndef soap_write___ns1__getSupportCity_
#define soap_write___ns1__getSupportCity_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getSupportCity_(soap, data), 0) || soap_put___ns1__getSupportCity_(soap, data, "-ns1:getSupportCity", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getSupportCity_ * SOAP_FMAC4 soap_get___ns1__getSupportCity_(struct soap*, struct __ns1__getSupportCity_ *, const char*, const char*);

#ifndef soap_read___ns1__getSupportCity_
#define soap_read___ns1__getSupportCity_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSupportCity_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getSupportCity_ * SOAP_FMAC2 soap_instantiate___ns1__getSupportCity_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getSupportCity_ * soap_new___ns1__getSupportCity_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getSupportCity_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getSupportCity_ * soap_new_req___ns1__getSupportCity_(struct soap *soap) { struct __ns1__getSupportCity_ *_p = soap_instantiate___ns1__getSupportCity_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportCity_(soap, _p); } return _p; }

inline struct __ns1__getSupportCity_ * soap_new_set___ns1__getSupportCity_(struct soap *soap, _ns1__getSupportCity *ns1__getSupportCity) { struct __ns1__getSupportCity_ *_p = soap_instantiate___ns1__getSupportCity_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportCity_(soap, _p); _p->ns1__getSupportCity = ns1__getSupportCity; } return _p; }

inline void soap_delete___ns1__getSupportCity_(struct soap *soap, struct __ns1__getSupportCity_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportCity_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getWeatherbyCityNamePro
#define SOAP_TYPE___ns1__getWeatherbyCityNamePro (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityNamePro(struct soap*, struct __ns1__getWeatherbyCityNamePro *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityNamePro(struct soap*, const struct __ns1__getWeatherbyCityNamePro *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityNamePro(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityNamePro *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityNamePro(struct soap*, const char*, struct __ns1__getWeatherbyCityNamePro *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityNamePro(struct soap*, const struct __ns1__getWeatherbyCityNamePro *, const char*, const char*);

#ifndef soap_write___ns1__getWeatherbyCityNamePro
#define soap_write___ns1__getWeatherbyCityNamePro(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getWeatherbyCityNamePro(soap, data), 0) || soap_put___ns1__getWeatherbyCityNamePro(soap, data, "-ns1:getWeatherbyCityNamePro", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityNamePro(struct soap*, struct __ns1__getWeatherbyCityNamePro *, const char*, const char*);

#ifndef soap_read___ns1__getWeatherbyCityNamePro
#define soap_read___ns1__getWeatherbyCityNamePro(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getWeatherbyCityNamePro(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getWeatherbyCityNamePro * SOAP_FMAC2 soap_instantiate___ns1__getWeatherbyCityNamePro(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getWeatherbyCityNamePro * soap_new___ns1__getWeatherbyCityNamePro(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getWeatherbyCityNamePro(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getWeatherbyCityNamePro * soap_new_req___ns1__getWeatherbyCityNamePro(struct soap *soap) { struct __ns1__getWeatherbyCityNamePro *_p = soap_instantiate___ns1__getWeatherbyCityNamePro(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityNamePro(soap, _p); } return _p; }

inline struct __ns1__getWeatherbyCityNamePro * soap_new_set___ns1__getWeatherbyCityNamePro(struct soap *soap, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro) { struct __ns1__getWeatherbyCityNamePro *_p = soap_instantiate___ns1__getWeatherbyCityNamePro(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityNamePro(soap, _p); _p->ns1__getWeatherbyCityNamePro = ns1__getWeatherbyCityNamePro; } return _p; }

inline void soap_delete___ns1__getWeatherbyCityNamePro(struct soap *soap, struct __ns1__getWeatherbyCityNamePro *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityNamePro(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getWeatherbyCityName
#define SOAP_TYPE___ns1__getWeatherbyCityName (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityName(struct soap*, struct __ns1__getWeatherbyCityName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityName(struct soap*, const struct __ns1__getWeatherbyCityName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityName(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityName *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityName(struct soap*, const char*, struct __ns1__getWeatherbyCityName *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityName(struct soap*, const struct __ns1__getWeatherbyCityName *, const char*, const char*);

#ifndef soap_write___ns1__getWeatherbyCityName
#define soap_write___ns1__getWeatherbyCityName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getWeatherbyCityName(soap, data), 0) || soap_put___ns1__getWeatherbyCityName(soap, data, "-ns1:getWeatherbyCityName", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getWeatherbyCityName * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityName(struct soap*, struct __ns1__getWeatherbyCityName *, const char*, const char*);

#ifndef soap_read___ns1__getWeatherbyCityName
#define soap_read___ns1__getWeatherbyCityName(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getWeatherbyCityName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getWeatherbyCityName * SOAP_FMAC2 soap_instantiate___ns1__getWeatherbyCityName(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getWeatherbyCityName * soap_new___ns1__getWeatherbyCityName(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getWeatherbyCityName(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getWeatherbyCityName * soap_new_req___ns1__getWeatherbyCityName(struct soap *soap) { struct __ns1__getWeatherbyCityName *_p = soap_instantiate___ns1__getWeatherbyCityName(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityName(soap, _p); } return _p; }

inline struct __ns1__getWeatherbyCityName * soap_new_set___ns1__getWeatherbyCityName(struct soap *soap, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName) { struct __ns1__getWeatherbyCityName *_p = soap_instantiate___ns1__getWeatherbyCityName(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getWeatherbyCityName(soap, _p); _p->ns1__getWeatherbyCityName = ns1__getWeatherbyCityName; } return _p; }

inline void soap_delete___ns1__getWeatherbyCityName(struct soap *soap, struct __ns1__getWeatherbyCityName *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getSupportDataSet
#define SOAP_TYPE___ns1__getSupportDataSet (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportDataSet(struct soap*, struct __ns1__getSupportDataSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportDataSet(struct soap*, const struct __ns1__getSupportDataSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportDataSet(struct soap*, const char*, int, const struct __ns1__getSupportDataSet *, const char*);
SOAP_FMAC3 struct __ns1__getSupportDataSet * SOAP_FMAC4 soap_in___ns1__getSupportDataSet(struct soap*, const char*, struct __ns1__getSupportDataSet *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportDataSet(struct soap*, const struct __ns1__getSupportDataSet *, const char*, const char*);

#ifndef soap_write___ns1__getSupportDataSet
#define soap_write___ns1__getSupportDataSet(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getSupportDataSet(soap, data), 0) || soap_put___ns1__getSupportDataSet(soap, data, "-ns1:getSupportDataSet", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getSupportDataSet * SOAP_FMAC4 soap_get___ns1__getSupportDataSet(struct soap*, struct __ns1__getSupportDataSet *, const char*, const char*);

#ifndef soap_read___ns1__getSupportDataSet
#define soap_read___ns1__getSupportDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSupportDataSet(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getSupportDataSet * SOAP_FMAC2 soap_instantiate___ns1__getSupportDataSet(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getSupportDataSet * soap_new___ns1__getSupportDataSet(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getSupportDataSet(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getSupportDataSet * soap_new_req___ns1__getSupportDataSet(struct soap *soap) { struct __ns1__getSupportDataSet *_p = soap_instantiate___ns1__getSupportDataSet(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportDataSet(soap, _p); } return _p; }

inline struct __ns1__getSupportDataSet * soap_new_set___ns1__getSupportDataSet(struct soap *soap, _ns1__getSupportDataSet *ns1__getSupportDataSet) { struct __ns1__getSupportDataSet *_p = soap_instantiate___ns1__getSupportDataSet(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportDataSet(soap, _p); _p->ns1__getSupportDataSet = ns1__getSupportDataSet; } return _p; }

inline void soap_delete___ns1__getSupportDataSet(struct soap *soap, struct __ns1__getSupportDataSet *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getSupportProvince
#define SOAP_TYPE___ns1__getSupportProvince (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportProvince(struct soap*, struct __ns1__getSupportProvince *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportProvince(struct soap*, const struct __ns1__getSupportProvince *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportProvince(struct soap*, const char*, int, const struct __ns1__getSupportProvince *, const char*);
SOAP_FMAC3 struct __ns1__getSupportProvince * SOAP_FMAC4 soap_in___ns1__getSupportProvince(struct soap*, const char*, struct __ns1__getSupportProvince *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportProvince(struct soap*, const struct __ns1__getSupportProvince *, const char*, const char*);

#ifndef soap_write___ns1__getSupportProvince
#define soap_write___ns1__getSupportProvince(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getSupportProvince(soap, data), 0) || soap_put___ns1__getSupportProvince(soap, data, "-ns1:getSupportProvince", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getSupportProvince * SOAP_FMAC4 soap_get___ns1__getSupportProvince(struct soap*, struct __ns1__getSupportProvince *, const char*, const char*);

#ifndef soap_read___ns1__getSupportProvince
#define soap_read___ns1__getSupportProvince(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSupportProvince(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getSupportProvince * SOAP_FMAC2 soap_instantiate___ns1__getSupportProvince(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getSupportProvince * soap_new___ns1__getSupportProvince(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getSupportProvince(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getSupportProvince * soap_new_req___ns1__getSupportProvince(struct soap *soap) { struct __ns1__getSupportProvince *_p = soap_instantiate___ns1__getSupportProvince(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportProvince(soap, _p); } return _p; }

inline struct __ns1__getSupportProvince * soap_new_set___ns1__getSupportProvince(struct soap *soap, _ns1__getSupportProvince *ns1__getSupportProvince) { struct __ns1__getSupportProvince *_p = soap_instantiate___ns1__getSupportProvince(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportProvince(soap, _p); _p->ns1__getSupportProvince = ns1__getSupportProvince; } return _p; }

inline void soap_delete___ns1__getSupportProvince(struct soap *soap, struct __ns1__getSupportProvince *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportProvince(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getSupportCity
#define SOAP_TYPE___ns1__getSupportCity (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportCity(struct soap*, struct __ns1__getSupportCity *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportCity(struct soap*, const struct __ns1__getSupportCity *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportCity(struct soap*, const char*, int, const struct __ns1__getSupportCity *, const char*);
SOAP_FMAC3 struct __ns1__getSupportCity * SOAP_FMAC4 soap_in___ns1__getSupportCity(struct soap*, const char*, struct __ns1__getSupportCity *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportCity(struct soap*, const struct __ns1__getSupportCity *, const char*, const char*);

#ifndef soap_write___ns1__getSupportCity
#define soap_write___ns1__getSupportCity(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__getSupportCity(soap, data), 0) || soap_put___ns1__getSupportCity(soap, data, "-ns1:getSupportCity", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__getSupportCity * SOAP_FMAC4 soap_get___ns1__getSupportCity(struct soap*, struct __ns1__getSupportCity *, const char*, const char*);

#ifndef soap_read___ns1__getSupportCity
#define soap_read___ns1__getSupportCity(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSupportCity(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__getSupportCity * SOAP_FMAC2 soap_instantiate___ns1__getSupportCity(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getSupportCity * soap_new___ns1__getSupportCity(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getSupportCity(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getSupportCity * soap_new_req___ns1__getSupportCity(struct soap *soap) { struct __ns1__getSupportCity *_p = soap_instantiate___ns1__getSupportCity(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportCity(soap, _p); } return _p; }

inline struct __ns1__getSupportCity * soap_new_set___ns1__getSupportCity(struct soap *soap, _ns1__getSupportCity *ns1__getSupportCity) { struct __ns1__getSupportCity *_p = soap_instantiate___ns1__getSupportCity(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getSupportCity(soap, _p); _p->ns1__getSupportCity = ns1__getSupportCity; } return _p; }

inline void soap_delete___ns1__getSupportCity(struct soap *soap, struct __ns1__getSupportCity *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportCity(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNamePro
#define SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNamePro (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, const char *, int, _ns1__getWeatherbyCityNamePro *const*, const char *);
SOAP_FMAC3 _ns1__getWeatherbyCityNamePro ** SOAP_FMAC4 soap_in_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, const char*, _ns1__getWeatherbyCityNamePro **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getWeatherbyCityNamePro
#define soap_write_PointerTo_ns1__getWeatherbyCityNamePro(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getWeatherbyCityNamePro(soap, data), 0) || soap_put_PointerTo_ns1__getWeatherbyCityNamePro(soap, data, "ns1:getWeatherbyCityNamePro", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getWeatherbyCityNamePro ** SOAP_FMAC4 soap_get_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getWeatherbyCityNamePro
#define soap_read_PointerTo_ns1__getWeatherbyCityNamePro(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getWeatherbyCityNamePro(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getWeatherbyCityName
#define SOAP_TYPE_PointerTo_ns1__getWeatherbyCityName (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getWeatherbyCityName(struct soap*, const char *, int, _ns1__getWeatherbyCityName *const*, const char *);
SOAP_FMAC3 _ns1__getWeatherbyCityName ** SOAP_FMAC4 soap_in_PointerTo_ns1__getWeatherbyCityName(struct soap*, const char*, _ns1__getWeatherbyCityName **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getWeatherbyCityName
#define soap_write_PointerTo_ns1__getWeatherbyCityName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getWeatherbyCityName(soap, data), 0) || soap_put_PointerTo_ns1__getWeatherbyCityName(soap, data, "ns1:getWeatherbyCityName", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getWeatherbyCityName ** SOAP_FMAC4 soap_get_PointerTo_ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getWeatherbyCityName
#define soap_read_PointerTo_ns1__getWeatherbyCityName(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getWeatherbyCityName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getSupportDataSet
#define SOAP_TYPE_PointerTo_ns1__getSupportDataSet (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportDataSet(struct soap*, const char *, int, _ns1__getSupportDataSet *const*, const char *);
SOAP_FMAC3 _ns1__getSupportDataSet ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportDataSet(struct soap*, const char*, _ns1__getSupportDataSet **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getSupportDataSet
#define soap_write_PointerTo_ns1__getSupportDataSet(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getSupportDataSet(soap, data), 0) || soap_put_PointerTo_ns1__getSupportDataSet(soap, data, "ns1:getSupportDataSet", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportDataSet ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getSupportDataSet
#define soap_read_PointerTo_ns1__getSupportDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getSupportDataSet(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getSupportProvince
#define SOAP_TYPE_PointerTo_ns1__getSupportProvince (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportProvince(struct soap*, const char *, int, _ns1__getSupportProvince *const*, const char *);
SOAP_FMAC3 _ns1__getSupportProvince ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportProvince(struct soap*, const char*, _ns1__getSupportProvince **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getSupportProvince
#define soap_write_PointerTo_ns1__getSupportProvince(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getSupportProvince(soap, data), 0) || soap_put_PointerTo_ns1__getSupportProvince(soap, data, "ns1:getSupportProvince", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportProvince ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getSupportProvince
#define soap_read_PointerTo_ns1__getSupportProvince(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getSupportProvince(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getSupportCity
#define SOAP_TYPE_PointerTo_ns1__getSupportCity (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportCity(struct soap*, _ns1__getSupportCity *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportCity(struct soap*, const char *, int, _ns1__getSupportCity *const*, const char *);
SOAP_FMAC3 _ns1__getSupportCity ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportCity(struct soap*, const char*, _ns1__getSupportCity **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportCity(struct soap*, _ns1__getSupportCity *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getSupportCity
#define soap_write_PointerTo_ns1__getSupportCity(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getSupportCity(soap, data), 0) || soap_put_PointerTo_ns1__getSupportCity(soap, data, "ns1:getSupportCity", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportCity ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportCity(struct soap*, _ns1__getSupportCity **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getSupportCity
#define soap_read_PointerTo_ns1__getSupportCity(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getSupportCity(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult
#define SOAP_TYPE_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, _ns1__getSupportDataSetResponse_getSupportDataSetResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char *, int, _ns1__getSupportDataSetResponse_getSupportDataSetResult *const*, const char *);
SOAP_FMAC3 _ns1__getSupportDataSetResponse_getSupportDataSetResult ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char*, _ns1__getSupportDataSetResponse_getSupportDataSetResult **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, _ns1__getSupportDataSetResponse_getSupportDataSetResult *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult
#define soap_write_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data), 0) || soap_put_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data, "ns1:getSupportDataSetResponse-getSupportDataSetResult", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__getSupportDataSetResponse_getSupportDataSetResult ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, _ns1__getSupportDataSetResponse_getSupportDataSetResult **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult
#define soap_read_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__ArrayOfString
#define SOAP_TYPE_PointerTons1__ArrayOfString (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfString(struct soap*, const char *, int, ns1__ArrayOfString *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfString ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfString(struct soap*, const char*, ns1__ArrayOfString **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__ArrayOfString
#define soap_write_PointerTons1__ArrayOfString(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__ArrayOfString(soap, data), 0) || soap_put_PointerTons1__ArrayOfString(soap, data, "ns1:ArrayOfString", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ArrayOfString ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString **, const char*, const char*);

#ifndef soap_read_PointerTons1__ArrayOfString
#define soap_read_PointerTons1__ArrayOfString(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ArrayOfString(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerTostring
#define soap_write_PointerTostring(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTostring(soap, data), 0) || soap_put_PointerTostring(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerTostring
#define soap_read_PointerTostring(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostring(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


/* _xsd__schema is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__xsd__schema
#define SOAP_TYPE__xsd__schema (7)
#endif

#define soap_default__xsd__schema(soap, a) soap_default_string(soap, a)


#define soap_serialize__xsd__schema soap_serialize_string


#define soap_out__xsd__schema soap_out_string


#define soap_in__xsd__schema soap_in_string


#define soap_put__xsd__schema soap_put_string


#define soap_get__xsd__schema soap_get_string


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
