/* soapStub.h
   Generated by gSOAP 2.8.22 from wth.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://WebXml.com.cn/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20822
# error "GSOAP VERSION 20822 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (8)
/* ns1:ArrayOfString */
class SOAP_CMAC ns1__ArrayOfString
{
public:
	int __sizestring;	/* sequence of elements <string> */
	char **string;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique type id SOAP_TYPE_ns1__ArrayOfString */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ArrayOfString() { ns1__ArrayOfString::soap_default(NULL); }
	virtual ~ns1__ArrayOfString() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getSupportCity
#define SOAP_TYPE__ns1__getSupportCity (9)
/* ns1:getSupportCity */
class SOAP_CMAC _ns1__getSupportCity
{
public:
	char *byProvinceName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique type id SOAP_TYPE__ns1__getSupportCity */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getSupportCity() { _ns1__getSupportCity::soap_default(NULL); }
	virtual ~_ns1__getSupportCity() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getSupportCityResponse
#define SOAP_TYPE__ns1__getSupportCityResponse (10)
/* ns1:getSupportCityResponse */
class SOAP_CMAC _ns1__getSupportCityResponse
{
public:
	ns1__ArrayOfString *getSupportCityResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique type id SOAP_TYPE__ns1__getSupportCityResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getSupportCityResponse() { _ns1__getSupportCityResponse::soap_default(NULL); }
	virtual ~_ns1__getSupportCityResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getSupportProvince
#define SOAP_TYPE__ns1__getSupportProvince (11)
/* ns1:getSupportProvince */
class SOAP_CMAC _ns1__getSupportProvince
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique type id SOAP_TYPE__ns1__getSupportProvince */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getSupportProvince() { _ns1__getSupportProvince::soap_default(NULL); }
	virtual ~_ns1__getSupportProvince() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getSupportProvinceResponse
#define SOAP_TYPE__ns1__getSupportProvinceResponse (12)
/* ns1:getSupportProvinceResponse */
class SOAP_CMAC _ns1__getSupportProvinceResponse
{
public:
	ns1__ArrayOfString *getSupportProvinceResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique type id SOAP_TYPE__ns1__getSupportProvinceResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getSupportProvinceResponse() { _ns1__getSupportProvinceResponse::soap_default(NULL); }
	virtual ~_ns1__getSupportProvinceResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getSupportDataSet
#define SOAP_TYPE__ns1__getSupportDataSet (13)
/* ns1:getSupportDataSet */
class SOAP_CMAC _ns1__getSupportDataSet
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique type id SOAP_TYPE__ns1__getSupportDataSet */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getSupportDataSet() { _ns1__getSupportDataSet::soap_default(NULL); }
	virtual ~_ns1__getSupportDataSet() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult
#define SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult (23)
/* ns1:getSupportDataSetResponse-getSupportDataSetResult */
class SOAP_CMAC _ns1__getSupportDataSetResponse_getSupportDataSetResult
{
public:
	char *xsd__schema;	/* required element of type xsd:schema */
	char *__any;
public:
	virtual int soap_type() const { return 23; } /* = unique type id SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getSupportDataSetResponse_getSupportDataSetResult() { _ns1__getSupportDataSetResponse_getSupportDataSetResult::soap_default(NULL); }
	virtual ~_ns1__getSupportDataSetResponse_getSupportDataSetResult() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getSupportDataSetResponse
#define SOAP_TYPE__ns1__getSupportDataSetResponse (14)
/* ns1:getSupportDataSetResponse */
class SOAP_CMAC _ns1__getSupportDataSetResponse
{
public:
	_ns1__getSupportDataSetResponse_getSupportDataSetResult *getSupportDataSetResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:getSupportDataSetResponse-getSupportDataSetResult */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 14; } /* = unique type id SOAP_TYPE__ns1__getSupportDataSetResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getSupportDataSetResponse() { _ns1__getSupportDataSetResponse::soap_default(NULL); }
	virtual ~_ns1__getSupportDataSetResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityName
#define SOAP_TYPE__ns1__getWeatherbyCityName (15)
/* ns1:getWeatherbyCityName */
class SOAP_CMAC _ns1__getWeatherbyCityName
{
public:
	char *theCityName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique type id SOAP_TYPE__ns1__getWeatherbyCityName */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getWeatherbyCityName() { _ns1__getWeatherbyCityName::soap_default(NULL); }
	virtual ~_ns1__getWeatherbyCityName() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNameResponse
#define SOAP_TYPE__ns1__getWeatherbyCityNameResponse (16)
/* ns1:getWeatherbyCityNameResponse */
class SOAP_CMAC _ns1__getWeatherbyCityNameResponse
{
public:
	ns1__ArrayOfString *getWeatherbyCityNameResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 16; } /* = unique type id SOAP_TYPE__ns1__getWeatherbyCityNameResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getWeatherbyCityNameResponse() { _ns1__getWeatherbyCityNameResponse::soap_default(NULL); }
	virtual ~_ns1__getWeatherbyCityNameResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNamePro
#define SOAP_TYPE__ns1__getWeatherbyCityNamePro (17)
/* ns1:getWeatherbyCityNamePro */
class SOAP_CMAC _ns1__getWeatherbyCityNamePro
{
public:
	char *theCityName;	/* optional element of type xsd:string */
	char *theUserID;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 17; } /* = unique type id SOAP_TYPE__ns1__getWeatherbyCityNamePro */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getWeatherbyCityNamePro() { _ns1__getWeatherbyCityNamePro::soap_default(NULL); }
	virtual ~_ns1__getWeatherbyCityNamePro() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNameProResponse
#define SOAP_TYPE__ns1__getWeatherbyCityNameProResponse (18)
/* ns1:getWeatherbyCityNameProResponse */
class SOAP_CMAC _ns1__getWeatherbyCityNameProResponse
{
public:
	ns1__ArrayOfString *getWeatherbyCityNameProResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 18; } /* = unique type id SOAP_TYPE__ns1__getWeatherbyCityNameProResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getWeatherbyCityNameProResponse() { _ns1__getWeatherbyCityNameProResponse::soap_default(NULL); }
	virtual ~_ns1__getWeatherbyCityNameProResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__DataSet
#define SOAP_TYPE__ns1__DataSet (19)
/* ns1:DataSet */
class SOAP_CMAC _ns1__DataSet
{
public:
	char *xsd__schema;	/* required element of type xsd:schema */
	char *__any;
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 19; } /* = unique type id SOAP_TYPE__ns1__DataSet */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__DataSet() { _ns1__DataSet::soap_default(NULL); }
	virtual ~_ns1__DataSet() { }
};
#endif

#ifndef SOAP_TYPE___ns1__getSupportCity
#define SOAP_TYPE___ns1__getSupportCity (28)
/* Operation wrapper: */
struct __ns1__getSupportCity
{
public:
	_ns1__getSupportCity *ns1__getSupportCity;	/* optional element of type ns1:getSupportCity */
public:
	int soap_type() const { return 28; } /* = unique type id SOAP_TYPE___ns1__getSupportCity */
};
#endif

#ifndef SOAP_TYPE___ns1__getSupportProvince
#define SOAP_TYPE___ns1__getSupportProvince (32)
/* Operation wrapper: */
struct __ns1__getSupportProvince
{
public:
	_ns1__getSupportProvince *ns1__getSupportProvince;	/* optional element of type ns1:getSupportProvince */
public:
	int soap_type() const { return 32; } /* = unique type id SOAP_TYPE___ns1__getSupportProvince */
};
#endif

#ifndef SOAP_TYPE___ns1__getSupportDataSet
#define SOAP_TYPE___ns1__getSupportDataSet (36)
/* Operation wrapper: */
struct __ns1__getSupportDataSet
{
public:
	_ns1__getSupportDataSet *ns1__getSupportDataSet;	/* optional element of type ns1:getSupportDataSet */
public:
	int soap_type() const { return 36; } /* = unique type id SOAP_TYPE___ns1__getSupportDataSet */
};
#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityName
#define SOAP_TYPE___ns1__getWeatherbyCityName (40)
/* Operation wrapper: */
struct __ns1__getWeatherbyCityName
{
public:
	_ns1__getWeatherbyCityName *ns1__getWeatherbyCityName;	/* optional element of type ns1:getWeatherbyCityName */
public:
	int soap_type() const { return 40; } /* = unique type id SOAP_TYPE___ns1__getWeatherbyCityName */
};
#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityNamePro
#define SOAP_TYPE___ns1__getWeatherbyCityNamePro (44)
/* Operation wrapper: */
struct __ns1__getWeatherbyCityNamePro
{
public:
	_ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro;	/* optional element of type ns1:getWeatherbyCityNamePro */
public:
	int soap_type() const { return 44; } /* = unique type id SOAP_TYPE___ns1__getWeatherbyCityNamePro */
};
#endif

#ifndef SOAP_TYPE___ns1__getSupportCity_
#define SOAP_TYPE___ns1__getSupportCity_ (46)
/* Operation wrapper: */
struct __ns1__getSupportCity_
{
public:
	_ns1__getSupportCity *ns1__getSupportCity;	/* optional element of type ns1:getSupportCity */
public:
	int soap_type() const { return 46; } /* = unique type id SOAP_TYPE___ns1__getSupportCity_ */
};
#endif

#ifndef SOAP_TYPE___ns1__getSupportProvince_
#define SOAP_TYPE___ns1__getSupportProvince_ (48)
/* Operation wrapper: */
struct __ns1__getSupportProvince_
{
public:
	_ns1__getSupportProvince *ns1__getSupportProvince;	/* optional element of type ns1:getSupportProvince */
public:
	int soap_type() const { return 48; } /* = unique type id SOAP_TYPE___ns1__getSupportProvince_ */
};
#endif

#ifndef SOAP_TYPE___ns1__getSupportDataSet_
#define SOAP_TYPE___ns1__getSupportDataSet_ (50)
/* Operation wrapper: */
struct __ns1__getSupportDataSet_
{
public:
	_ns1__getSupportDataSet *ns1__getSupportDataSet;	/* optional element of type ns1:getSupportDataSet */
public:
	int soap_type() const { return 50; } /* = unique type id SOAP_TYPE___ns1__getSupportDataSet_ */
};
#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityName_
#define SOAP_TYPE___ns1__getWeatherbyCityName_ (52)
/* Operation wrapper: */
struct __ns1__getWeatherbyCityName_
{
public:
	_ns1__getWeatherbyCityName *ns1__getWeatherbyCityName;	/* optional element of type ns1:getWeatherbyCityName */
public:
	int soap_type() const { return 52; } /* = unique type id SOAP_TYPE___ns1__getWeatherbyCityName_ */
};
#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityNamePro_
#define SOAP_TYPE___ns1__getWeatherbyCityNamePro_ (54)
/* Operation wrapper: */
struct __ns1__getWeatherbyCityNamePro_
{
public:
	_ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro;	/* optional element of type ns1:getWeatherbyCityNamePro */
public:
	int soap_type() const { return 54; } /* = unique type id SOAP_TYPE___ns1__getWeatherbyCityNamePro_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (55)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 55; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (56)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 56; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (58)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 58; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (61)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 61; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (62)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 62; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__xsd__schema
#define SOAP_TYPE__xsd__schema (7)
typedef char *_xsd__schema;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__getSupportCity(struct soap*, _ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getSupportCity_(struct soap*, _ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getSupportProvince_(struct soap*, _ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getSupportDataSet_(struct soap*, _ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getWeatherbyCityName_(struct soap*, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getWeatherbyCityNamePro_(struct soap*, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getSupportCity(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getSupportProvince(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getSupportDataSet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getWeatherbyCityName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getWeatherbyCityNamePro(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getSupportCity_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getSupportProvince_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getSupportDataSet_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getWeatherbyCityName_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getWeatherbyCityNamePro_(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSupportCity(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSupportProvince(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSupportDataSet(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getWeatherbyCityName(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getWeatherbyCityNamePro(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSupportCity_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSupportProvince_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSupportDataSet_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getWeatherbyCityName_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getWeatherbyCityNamePro_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse);

#endif

/* End of soapStub.h */
