/* soapStub.h
   Generated by gSOAP 2.8.22 from wth.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20822
# error "GSOAP VERSION 20822 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__ns1__HelloWorld
#define SOAP_TYPE__ns1__HelloWorld (7)
/* ns1:HelloWorld */
class SOAP_CMAC _ns1__HelloWorld
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique type id SOAP_TYPE__ns1__HelloWorld */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__HelloWorld() { _ns1__HelloWorld::soap_default(NULL); }
	virtual ~_ns1__HelloWorld() { }
};
#endif

#ifndef SOAP_TYPE__ns1__HelloWorldResponse
#define SOAP_TYPE__ns1__HelloWorldResponse (8)
/* ns1:HelloWorldResponse */
class SOAP_CMAC _ns1__HelloWorldResponse
{
public:
	char *HelloWorldResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique type id SOAP_TYPE__ns1__HelloWorldResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__HelloWorldResponse() { _ns1__HelloWorldResponse::soap_default(NULL); }
	virtual ~_ns1__HelloWorldResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__add_USCOREmaterial
#define SOAP_TYPE__ns1__add_USCOREmaterial (9)
/* ns1:add_material */
class SOAP_CMAC _ns1__add_USCOREmaterial
{
public:
	char *strRecID;	/* optional element of type xsd:string */
	char *strClueID;	/* optional element of type xsd:string */
	char *strUser;	/* optional element of type xsd:string */
	char *strFilePath;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique type id SOAP_TYPE__ns1__add_USCOREmaterial */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__add_USCOREmaterial() { _ns1__add_USCOREmaterial::soap_default(NULL); }
	virtual ~_ns1__add_USCOREmaterial() { }
};
#endif

#ifndef SOAP_TYPE__ns1__add_USCOREmaterialResponse
#define SOAP_TYPE__ns1__add_USCOREmaterialResponse (10)
/* ns1:add_materialResponse */
class SOAP_CMAC _ns1__add_USCOREmaterialResponse
{
public:
	bool add_USCOREmaterialResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *strFtpPath;	/* optional element of type xsd:string */
	char *strUserName;	/* optional element of type xsd:string */
	char *strPassword;	/* optional element of type xsd:string */
	char *strMsg;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique type id SOAP_TYPE__ns1__add_USCOREmaterialResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__add_USCOREmaterialResponse() { _ns1__add_USCOREmaterialResponse::soap_default(NULL); }
	virtual ~_ns1__add_USCOREmaterialResponse() { }
};
#endif

#ifndef SOAP_TYPE___ns1__HelloWorld
#define SOAP_TYPE___ns1__HelloWorld (16)
/* Operation wrapper: */
struct __ns1__HelloWorld
{
public:
	_ns1__HelloWorld *ns1__HelloWorld;	/* optional element of type ns1:HelloWorld */
public:
	int soap_type() const { return 16; } /* = unique type id SOAP_TYPE___ns1__HelloWorld */
};
#endif

#ifndef SOAP_TYPE___ns1__add_USCOREmaterial
#define SOAP_TYPE___ns1__add_USCOREmaterial (20)
/* Operation wrapper: */
struct __ns1__add_USCOREmaterial
{
public:
	_ns1__add_USCOREmaterial *ns1__add_USCOREmaterial;	/* optional element of type ns1:add_material */
public:
	int soap_type() const { return 20; } /* = unique type id SOAP_TYPE___ns1__add_USCOREmaterial */
};
#endif

#ifndef SOAP_TYPE___ns1__HelloWorld_
#define SOAP_TYPE___ns1__HelloWorld_ (22)
/* Operation wrapper: */
struct __ns1__HelloWorld_
{
public:
	_ns1__HelloWorld *ns1__HelloWorld;	/* optional element of type ns1:HelloWorld */
public:
	int soap_type() const { return 22; } /* = unique type id SOAP_TYPE___ns1__HelloWorld_ */
};
#endif

#ifndef SOAP_TYPE___ns1__add_USCOREmaterial_
#define SOAP_TYPE___ns1__add_USCOREmaterial_ (24)
/* Operation wrapper: */
struct __ns1__add_USCOREmaterial_
{
public:
	_ns1__add_USCOREmaterial *ns1__add_USCOREmaterial;	/* optional element of type ns1:add_material */
public:
	int soap_type() const { return 24; } /* = unique type id SOAP_TYPE___ns1__add_USCOREmaterial_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (25)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 25; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (26)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 26; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (28)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 28; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (31)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 31; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (32)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 32; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__HelloWorld(struct soap*, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__add_USCOREmaterial(struct soap*, _ns1__add_USCOREmaterial *ns1__add_USCOREmaterial, _ns1__add_USCOREmaterialResponse &ns1__add_USCOREmaterialResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__HelloWorld_(struct soap*, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__add_USCOREmaterial_(struct soap*, _ns1__add_USCOREmaterial *ns1__add_USCOREmaterial, _ns1__add_USCOREmaterialResponse &ns1__add_USCOREmaterialResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__HelloWorld(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__add_USCOREmaterial(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__HelloWorld_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__add_USCOREmaterial_(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__HelloWorld(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__add_USCOREmaterial(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__add_USCOREmaterial *ns1__add_USCOREmaterial, _ns1__add_USCOREmaterialResponse &ns1__add_USCOREmaterialResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__HelloWorld_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__add_USCOREmaterial_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__add_USCOREmaterial *ns1__add_USCOREmaterial, _ns1__add_USCOREmaterialResponse &ns1__add_USCOREmaterialResponse);

#endif

/* End of soapStub.h */
