/* wth.h
   Generated by wsdl2h 2.8.22 from http://202.20.2.96/ws_material/ws_material.asmx?wsdl and typemap.dat
   2015-07-27 01:54:59 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2014 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on wth.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://tempuri.org/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
//gsoap ns1   schema namespace:	http://tempuri.org/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class _ns1__HelloWorld.
class _ns1__HelloWorld;

//  Forward declaration of class _ns1__HelloWorldResponse.
class _ns1__HelloWorldResponse;

//  Forward declaration of class _ns1__add_USCOREmaterial.
class _ns1__add_USCOREmaterial;

//  Forward declaration of class _ns1__add_USCOREmaterialResponse.
class _ns1__add_USCOREmaterialResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://tempuri.org/":HelloWorld
/// @brief "http://tempuri.org/":HelloWorld is a complexType.
///
/// class _ns1__HelloWorld operations:
/// - soap_new__ns1__HelloWorld(soap*) allocate
/// - soap_new__ns1__HelloWorld(soap*, int num) allocate array
/// - soap_new_req__ns1__HelloWorld(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__HelloWorld(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__HelloWorld(soap*, _ns1__HelloWorld*) deserialize from a stream
/// - int soap_write__ns1__HelloWorld(soap, _ns1__HelloWorld*) serialize to a stream
class _ns1__HelloWorld
{ public:
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":HelloWorldResponse
/// @brief "http://tempuri.org/":HelloWorldResponse is a complexType.
///
/// class _ns1__HelloWorldResponse operations:
/// - soap_new__ns1__HelloWorldResponse(soap*) allocate
/// - soap_new__ns1__HelloWorldResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__HelloWorldResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__HelloWorldResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__HelloWorldResponse(soap*, _ns1__HelloWorldResponse*) deserialize from a stream
/// - int soap_write__ns1__HelloWorldResponse(soap, _ns1__HelloWorldResponse*) serialize to a stream
class _ns1__HelloWorldResponse
{ public:
/// Element "HelloWorldResult" of XSD type xs:string.
    char*                                HelloWorldResult               0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":add_material
/// @brief "http://tempuri.org/":add_material is a complexType.
///
/// class _ns1__add_USCOREmaterial operations:
/// - soap_new__ns1__add_USCOREmaterial(soap*) allocate
/// - soap_new__ns1__add_USCOREmaterial(soap*, int num) allocate array
/// - soap_new_req__ns1__add_USCOREmaterial(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__add_USCOREmaterial(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__add_USCOREmaterial(soap*, _ns1__add_USCOREmaterial*) deserialize from a stream
/// - int soap_write__ns1__add_USCOREmaterial(soap, _ns1__add_USCOREmaterial*) serialize to a stream
class _ns1__add_USCOREmaterial
{ public:
/// Element "strRecID" of XSD type xs:string.
    char*                                strRecID                       0;	///< Optional element.
/// Element "strClueID" of XSD type xs:string.
    char*                                strClueID                      0;	///< Optional element.
/// Element "strUser" of XSD type xs:string.
    char*                                strUser                        0;	///< Optional element.
/// Element "strFilePath" of XSD type xs:string.
    char*                                strFilePath                    0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":add_materialResponse
/// @brief "http://tempuri.org/":add_materialResponse is a complexType.
///
/// class _ns1__add_USCOREmaterialResponse operations:
/// - soap_new__ns1__add_USCOREmaterialResponse(soap*) allocate
/// - soap_new__ns1__add_USCOREmaterialResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__add_USCOREmaterialResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__add_USCOREmaterialResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__add_USCOREmaterialResponse(soap*, _ns1__add_USCOREmaterialResponse*) deserialize from a stream
/// - int soap_write__ns1__add_USCOREmaterialResponse(soap, _ns1__add_USCOREmaterialResponse*) serialize to a stream
class _ns1__add_USCOREmaterialResponse
{ public:
/// Element "add_materialResult" of XSD type xs:boolean.
    bool                                 add_USCOREmaterialResult       1;	///< Required element.
/// Element "strFtpPath" of XSD type xs:string.
    char*                                strFtpPath                     0;	///< Optional element.
/// Element "strUserName" of XSD type xs:string.
    char*                                strUserName                    0;	///< Optional element.
/// Element "strPassword" of XSD type xs:string.
    char*                                strPassword                    0;	///< Optional element.
/// Element "strMsg" of XSD type xs:string.
    char*                                strMsg                         0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	ws_USCOREmaterialSoap 
//gsoap ns1  service type:	ws_USCOREmaterialSoap 
//gsoap ns1  service port:	http://202.20.2.96/ws_material/ws_material.asmx 
//gsoap ns1  service namespace:	http://tempuri.org/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref ws_USCOREmaterialSoap

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page ws_USCOREmaterialSoap Binding "ws_USCOREmaterialSoap"

@section ws_USCOREmaterialSoap_operations Operations of Binding "ws_USCOREmaterialSoap"

  - @ref __ns1__HelloWorld

  - @ref __ns1__add_USCOREmaterial

  - @ref __ns1__HelloWorld_

  - @ref __ns1__add_USCOREmaterial_

@section ws_USCOREmaterialSoap_ports Endpoints of Binding "ws_USCOREmaterialSoap"

  - http://202.20.2.96/ws_material/ws_material.asmx

@note Multiple service bindings collected as one, use wsdl2h option -Nname to produce a separate service for each binding


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   ws_USCOREmaterialSoap                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__HelloWorld                                                        *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__HelloWorld" of service binding "ws_USCOREmaterialSoap".

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/HelloWorld"

  - Addressing input action: "http://tempuri.org/HelloWorld"

  - Addressing output action: "http://tempuri.org/HelloWorldResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__HelloWorld(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__HelloWorld*                   ns1__HelloWorld,
    // output parameters:
    _ns1__HelloWorldResponse           &ns1__HelloWorldResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__HelloWorld(
    struct soap *soap,
    // input parameters:
    _ns1__HelloWorld*                   ns1__HelloWorld,
    // output parameters:
    _ns1__HelloWorldResponse           &ns1__HelloWorldResponse
  );
@endcode

C++ proxy class (defined in soapws_USCOREmaterialSoapProxy.h):
@code
  class ws_USCOREmaterialSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapws_USCOREmaterialSoapService.h):
@code
  class ws_USCOREmaterialSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	HelloWorld SOAP
//gsoap ns1  service method-style:	HelloWorld document
//gsoap ns1  service method-encoding:	HelloWorld literal
//gsoap ns1  service method-input-action:	HelloWorld http://tempuri.org/HelloWorld
//gsoap ns1  service method-output-action:	HelloWorld http://tempuri.org/HelloWorldResponse
int __ns1__HelloWorld(
    _ns1__HelloWorld*                   ns1__HelloWorld,	///< Input parameter
    _ns1__HelloWorldResponse           &ns1__HelloWorldResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__add_USCOREmaterial                                                *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__add_USCOREmaterial" of service binding "ws_USCOREmaterialSoap".

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/add_material"

  - Addressing input action: "http://tempuri.org/add_material"

  - Addressing output action: "http://tempuri.org/add_materialResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__add_USCOREmaterial(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__add_USCOREmaterial*           ns1__add_USCOREmaterial,
    // output parameters:
    _ns1__add_USCOREmaterialResponse   &ns1__add_USCOREmaterialResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__add_USCOREmaterial(
    struct soap *soap,
    // input parameters:
    _ns1__add_USCOREmaterial*           ns1__add_USCOREmaterial,
    // output parameters:
    _ns1__add_USCOREmaterialResponse   &ns1__add_USCOREmaterialResponse
  );
@endcode

C++ proxy class (defined in soapws_USCOREmaterialSoapProxy.h):
@code
  class ws_USCOREmaterialSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapws_USCOREmaterialSoapService.h):
@code
  class ws_USCOREmaterialSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	add_USCOREmaterial SOAP
//gsoap ns1  service method-style:	add_USCOREmaterial document
//gsoap ns1  service method-encoding:	add_USCOREmaterial literal
//gsoap ns1  service method-input-action:	add_USCOREmaterial http://tempuri.org/add_material
//gsoap ns1  service method-output-action:	add_USCOREmaterial http://tempuri.org/add_materialResponse
int __ns1__add_USCOREmaterial(
    _ns1__add_USCOREmaterial*           ns1__add_USCOREmaterial,	///< Input parameter
    _ns1__add_USCOREmaterialResponse   &ns1__add_USCOREmaterialResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__HelloWorld_                                                       *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__HelloWorld_" of service binding "ws_USCOREmaterialSoap".

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/HelloWorld"

  - Addressing input action: "http://tempuri.org/HelloWorld"

  - Addressing output action: "http://tempuri.org/HelloWorldResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__HelloWorld_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__HelloWorld*                   ns1__HelloWorld,
    // output parameters:
    _ns1__HelloWorldResponse           &ns1__HelloWorldResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__HelloWorld_(
    struct soap *soap,
    // input parameters:
    _ns1__HelloWorld*                   ns1__HelloWorld,
    // output parameters:
    _ns1__HelloWorldResponse           &ns1__HelloWorldResponse
  );
@endcode

C++ proxy class (defined in soapws_USCOREmaterialSoapProxy.h):
@code
  class ws_USCOREmaterialSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapws_USCOREmaterialSoapService.h):
@code
  class ws_USCOREmaterialSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	HelloWorld_ SOAP
//gsoap ns1  service method-style:	HelloWorld_ document
//gsoap ns1  service method-encoding:	HelloWorld_ literal
//gsoap ns1  service method-input-action:	HelloWorld_ http://tempuri.org/HelloWorld
//gsoap ns1  service method-output-action:	HelloWorld_ http://tempuri.org/HelloWorldResponse
int __ns1__HelloWorld_(
    _ns1__HelloWorld*                   ns1__HelloWorld,	///< Input parameter
    _ns1__HelloWorldResponse           &ns1__HelloWorldResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__add_USCOREmaterial_                                               *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__add_USCOREmaterial_" of service binding "ws_USCOREmaterialSoap".

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/add_material"

  - Addressing input action: "http://tempuri.org/add_material"

  - Addressing output action: "http://tempuri.org/add_materialResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__add_USCOREmaterial_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__add_USCOREmaterial*           ns1__add_USCOREmaterial,
    // output parameters:
    _ns1__add_USCOREmaterialResponse   &ns1__add_USCOREmaterialResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__add_USCOREmaterial_(
    struct soap *soap,
    // input parameters:
    _ns1__add_USCOREmaterial*           ns1__add_USCOREmaterial,
    // output parameters:
    _ns1__add_USCOREmaterialResponse   &ns1__add_USCOREmaterialResponse
  );
@endcode

C++ proxy class (defined in soapws_USCOREmaterialSoapProxy.h):
@code
  class ws_USCOREmaterialSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapws_USCOREmaterialSoapService.h):
@code
  class ws_USCOREmaterialSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	add_USCOREmaterial_ SOAP
//gsoap ns1  service method-style:	add_USCOREmaterial_ document
//gsoap ns1  service method-encoding:	add_USCOREmaterial_ literal
//gsoap ns1  service method-input-action:	add_USCOREmaterial_ http://tempuri.org/add_material
//gsoap ns1  service method-output-action:	add_USCOREmaterial_ http://tempuri.org/add_materialResponse
int __ns1__add_USCOREmaterial_(
    _ns1__add_USCOREmaterial*           ns1__add_USCOREmaterial,	///< Input parameter
    _ns1__add_USCOREmaterialResponse   &ns1__add_USCOREmaterialResponse	///< Output parameter
);

/**

@page ws_USCOREmaterialSoap Binding "ws_USCOREmaterialSoap"

@section ws_USCOREmaterialSoap_policy_enablers Policy Enablers of Binding "ws_USCOREmaterialSoap"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://tempuri.org/"

  - <HelloWorld> @ref _ns1__HelloWorld
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__HelloWorld(struct soap*, _ns1__HelloWorld*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__HelloWorld(struct soap*, _ns1__HelloWorld*);
    @endcode

  - <HelloWorldResponse> @ref _ns1__HelloWorldResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__HelloWorldResponse(struct soap*, _ns1__HelloWorldResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__HelloWorldResponse(struct soap*, _ns1__HelloWorldResponse*);
    @endcode

  - <add_material> @ref _ns1__add_USCOREmaterial
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__add_USCOREmaterial(struct soap*, _ns1__add_USCOREmaterial*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__add_USCOREmaterial(struct soap*, _ns1__add_USCOREmaterial*);
    @endcode

  - <add_materialResponse> @ref _ns1__add_USCOREmaterialResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__add_USCOREmaterialResponse(struct soap*, _ns1__add_USCOREmaterialResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__add_USCOREmaterialResponse(struct soap*, _ns1__add_USCOREmaterialResponse*);
    @endcode

*/

/* End of wth.h */
